apiVersion: v1
kind: Service
metadata:
  name: redis-access-service
  namespace: redis-cluster
  labels:
    app: redis
spec:
  ports:
  - name: redis-port
    protocol: "TCP"
    port: 6379
    targetPort: 6379
    nodePort: 30379
  selector:
    app: redis
    appCluster: redis-cluster
  type: NodePort
